# frozen_string_literal: true

require "fileutils"

module Backpressure
  module Compiler
    class RubocopCompiler
      def initialize(output_dir:)
        @output_dir = output_dir
      end

      def self.compilable?(check_class)
        return false unless check_class.respond_to?(:compilable?) && check_class.compilable?
        contexts = check_class.required_contexts || []
        contexts == [:ast]
      end

      def compile(check_class)
        FileUtils.mkdir_p(@output_dir)

        cop_name = check_class.check_name
        file_name = cop_name.gsub(/([a-z])([A-Z])/, '\1_\2').downcase
        output_path = File.join(@output_dir, "#{file_name}.rb")

        content = generate_cop(cop_name, check_class)
        File.write(output_path, content)
        output_path
      end

      private

      def generate_cop(cop_name, check_class)
        <<~RUBY
          # frozen_string_literal: true

          # Auto-generated by backpressure compile --rubocop
          # Source: #{check_class.name || cop_name}

          module RuboCop
            module Cop
              module Backpressure
                class #{cop_name} < Base
                  MSG = "Backpressure/#{cop_name}: violation detected"

                  def on_new_investigation
                    @check = create_backpressure_check
                    context = ::Backpressure::Contexts::AstContext.new(
                      source: processed_source.buffer.source,
                      file_path: processed_source.file_path
                    )
                    @check.run(context)
                    @check.violations.each do |v|
                      node = find_node_at(v.line, v.column)
                      add_offense(node || processed_source.ast, message: v.message) if node || processed_source.ast
                    end
                  end

                  private

                  def create_backpressure_check
                    ::#{check_class.name || cop_name}.new
                  end

                  def find_node_at(line, column)
                    processed_source.ast.each_node do |node|
                      return node if node.loc&.line == line
                    end
                    nil
                  end
                end
              end
            end
          end
        RUBY
      end
    end
  end
end
